### ISSUE TITLE
Configure role per database

### ISSUE THREAD

**Issue by danielwestermann** [dalibo/ldap2pg#584] opened 2024-01-30 13:30 UTC
Hi,

first of all thank you for ldap2pg, great tool.

I have a question for which I cannot find the answer in the docs or in any of issues. What I want to do is something like this:

`alter { role } in database { database } set session authorization  b;`

The reason is that roles shall switch session authorization automatically and I want to avoid having them issuing "set role" manually.

Is something like this possible?

Best regards
Daniel

**Comment by bersace** [comment] 2024-04-08 09:16
ldap2pg handle global role configuration, not per database.

**Comment by bersace** [comment] 2024-04-08 09:24
Duplicate of #572 . Please reopen if I'm wrong.

**Closed by bersace** 2024-04-08 09:24 UTC
Labels: feature
